/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SystemForm.java
 *
 * Created on Oct 5, 2011, 9:56:56 PM
 */
package systemForm;

import java.util.HashSet;

/**
 *
 * @author Dimzin
 */
public class SystemForm extends javax.swing.JFrame {

    /** Creates new form SystemForm */
    public SystemForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        converterComponent1 = new converterComponent.ConverterComponent();
        jLabel1 = new javax.swing.JLabel();
        numberInputField = new javax.swing.JTextField();
        inputSystemBaseField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        decimalResultShower = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        desiredSystemBaseField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        desiredSystemNumberOutputer = new javax.swing.JTextField();
        convertToDesiredSystem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        restarter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        exceptionLabel = new javax.swing.JLabel();
        restartLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please enter the number:");

        inputSystemBaseField.setName(""); // NOI18N
        inputSystemBaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSystemBaseFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Please enter the base system number:");

        jLabel4.setText("The input number in decimal system:");

        jLabel5.setText("Please enter the desired system base:");

        jLabel6.setText("The number in the desired system base:");

        convertToDesiredSystem.setText("Convert to Desired System");
        convertToDesiredSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertToDesiredSystemActionPerformed(evt);
            }
        });

        jLabel7.setText("Convert to the desired system:");

        restarter.setText("Restart");
        restarter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarterActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("System Converter:");

        jLabel10.setText("Exceptions handler:");

        exceptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        restartLabel.setText("Press Restart if you input something wrong:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSystemBaseField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(numberInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(convertToDesiredSystem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desiredSystemBaseField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(restartLabel))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restarter, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(exceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(decimalResultShower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(desiredSystemNumberOutputer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputSystemBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(desiredSystemBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(convertToDesiredSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalResultShower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desiredSystemNumberOutputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restartLabel)
                    .addComponent(restarter))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(exceptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void convertToDesiredSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertToDesiredSystemActionPerformed
    if (converterComponent1.isProcessable()) {
        converterComponent1.setInputValue(Integer.parseInt(numberInputField.getText()));
        converterComponent1.setSystemType(Integer.parseInt(inputSystemBaseField.getText()), Integer.parseInt(desiredSystemBaseField.getText()));

        if (converterComponent1.isInputCorrect()) {
            converterComponent1.setConvertedToDecimalValue(converterComponent1.getInputValue(), converterComponent1.getInputSystemType());
            decimalResultShower.setText(String.valueOf(converterComponent1.getConvertedToDecimalValue()));
            converterComponent1.setConvertedValue(converterComponent1.getConvertedToDecimalValue(), converterComponent1.getDestinationSystemType());
            desiredSystemNumberOutputer.setText(converterComponent1.getConvertedValue());
        }
    }
    exceptionLabel.setText(converterComponent1.getError());

}//GEN-LAST:event_convertToDesiredSystemActionPerformed

private void restarterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarterActionPerformed
    numberInputField.setText(null);
    inputSystemBaseField.setText(null);
    decimalResultShower.setText(null);
    desiredSystemBaseField.setText(null);
    desiredSystemNumberOutputer.setText(null);
    exceptionLabel.setText(null);
    converterComponent1.setProcessable(true);
    converterComponent1.setIsInputCorrect(true);
    converterComponent1.setError(0);
}//GEN-LAST:event_restarterActionPerformed

private void inputSystemBaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSystemBaseFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_inputSystemBaseFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SystemForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertToDesiredSystem;
    private converterComponent.ConverterComponent converterComponent1;
    private javax.swing.JTextField decimalResultShower;
    private javax.swing.JTextField desiredSystemBaseField;
    private javax.swing.JTextField desiredSystemNumberOutputer;
    private javax.swing.JLabel exceptionLabel;
    private javax.swing.JTextField inputSystemBaseField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField numberInputField;
    private javax.swing.JLabel restartLabel;
    private javax.swing.JButton restarter;
    // End of variables declaration//GEN-END:variables
}
